package com.sa001;

/**
 * Represents a single sales transaction.
 * Each record includes date, region, product, quantity sold, and price per unit.
 */
public class SaleRecord {
    private final String date;
    private final String region;
    private final String product;
    private final int quantity;
    private final double price;

    /**
     * Constructs a new SaleRecord.
     *
     * @param date     date of the sale
     * @param region   region where sale occurred
     * @param product  product sold
     * @param quantity number of units sold
     * @param price    price per unit
     */
    public SaleRecord(String date, String region, String product, int quantity, double price) {
        this.date = date;
        this.region = region;
        this.product = product;
        this.quantity = quantity;
        this.price = price;
    }

    public String getDate() { return date; }
    public String getRegion() { return region; }
    public String getProduct() { return product; }
    public int getQuantity() { return quantity; }
    public double getPrice() { return price; }

    /**
     * @return total revenue generated by this sale (price * quantity).
     */
    public double getTotal() { return quantity * price; }

    @Override
    public String toString() {
        return "SaleRecord{" +
                "date='" + date + '\'' +
                ", region='" + region + '\'' +
                ", product='" + product + '\'' +
                ", quantity=" + quantity +
                ", price=" + price +
                '}';
    }
}
